### ISSUE TITLE
C: WASM64

### ISSUE THREAD

**Issue by mcandre** [mcandre/tonixxx#142]
https://webassembly.org/

* [x] Pending https://github.com/mcandre/cartel/issues/31

**Comment by mcandre** [comment]
Draft so far:

https://github.com/mcandre/tonixxx/tree/issue-142

For some reason, the Emscripten setup script is failing:

```console
Adding directories to PATH:
PATH += /home/vagrant/emsdk

Setting environment variables:
EMSDK = /home/vagrant/emsdk
EM_CONFIG = /home/vagrant/.emscripten

Traceback (most recent call last):
  File "./emsdk", line 2437, in <module>
    sys.exit(main())
  File "./emsdk", line 2333, in main
    open(EMSDK_SET_ENV, 'w').write(env_string)
IOError: [Errno 13] Permission denied: 'emsdk_set_env.sh'
/home/vagrant/emsdk/emsdk_env.sh: line 26: ./emsdk_set_env.sh: No such file or directory
-- Configuring incomplete, errors occurred!
```
